name = "webhookdispatcher"
main = "src/index.ts"
compatibility_date = "2024-02-08"

[[durable_objects.bindings]]
name = "WEBHOOK"
class_name = "Webhook"

[[migrations]]
tag = "v1"
new_classes = ["Webhook"]

[vars]
VERSION = "local"
