name = "webhookdispatcher"
main = "src/index.ts"
compatibility_date = "2024-02-08"
workers_dev = false

[[routes]]
pattern = "webhookdispatcher.broswen.com"
custom_domain = true

[vars]
VERSION = "local"
PRIVATE_KEY_ALG = "RS256"
# set using wrangler
# PRIVATE_KEY = ""

[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "webhookdispatcher"

[[durable_objects.bindings]]
name = "WEBHOOK"
class_name = "Webhook"

[[migrations]]
tag = "v1"
new_classes = ["Webhook"]

